### ISSUE TITLE
[BUG] Batch with a single request duplicates the event

### ISSUE THREAD

**Issue by GustavoOS** [upstash/qstash-go#4]
I have the following method to publish the batch:

```go
func PublishSomething(ids []int64) (error) {
	req := make([]qstash.BatchJSONOptions, len(ids))
	for index, id:= range ids {
		req[index] = qstash.BatchJSONOptions {
			Url: fmt.Sprintf("%s/something?id=%d", url, id),
			Headers:  map[string]string{
				"Upstash-Method": "DELETE",
			},
		}
	}
	_, err := QClient.BatchJSON(req)
	return err
}
```

If I call it like

```go
ids := []int64{5}
PublishSomething(ids)
```

Then 2 events are added to QStash
![image](https://github.com/user-attachments/assets/dcab8ccc-1d32-4a53-b6d8-10415693da82)

**Comment by sancar** [comment]
Hi, I have just tried your code as is. This is what I saw on the console related to this call, and these are expected. 
<img width="952" alt="Screenshot 2024-10-31 at 10 04 19" src="https://github.com/user-attachments/assets/8c48497e-f502-4ba6-b084-9f90448b77b4">

You can check the following documents to see expected events per publish. 
https://upstash.com/docs/qstash/howto/debug-logs

**Comment by sancar** [comment]
Hi @GustavoOS, closing the issue since we could not hear from you. Feel free to reopen if issue persists.
